obj-m += cr3dump.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

install:
	sudo insmod cr3dump.ko

uninstall:
	sudo rmmod cr3dump
